
package co.experian.computec.saml.ws.validadortoken.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* WsValidadorTokenSamlService service = new WsValidadorTokenSamlService();
* WsValidadorTokenSaml portType = service.getWsValidadorTokenSamlPort();
* portType.validateToken(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name="WsValidadorTokenSamlService",targetNamespace="http://co.experian.computec.saml.ws.validadortoken/",wsdlLocation="http://127.0.0.1:8080/WsValidationTokenSAML-1.0/WsValidadorTokenSamlService?wsdl")
public class WsValidadorTokenSamlService extends Service{

    private final static URL WSVALIDADORTOKENSAMLSERVICE_WSDL_LOCATION;
    private final static Logger logger=Logger.getLogger(co.experian.computec.saml.ws.validadortoken.cliente.WsValidadorTokenSamlService.class.getName());

    static{
        URL url=null;
        try{
            URL baseUrl;
            baseUrl=co.experian.computec.saml.ws.validadortoken.cliente.WsValidadorTokenSamlService.class.getResource(".");
            url=new URL(baseUrl,"http://127.0.0.1:8080/WsValidationTokenSAML-1.0/WsValidadorTokenSamlService?wsdl");
        }
        catch(MalformedURLException e){
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/WsValidationTokenSAML-1.0/WsValidadorTokenSamlService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSVALIDADORTOKENSAMLSERVICE_WSDL_LOCATION=url;
    }

    public WsValidadorTokenSamlService(URL wsdlLocation,QName serviceName){
        super(wsdlLocation,serviceName);
    }

    public WsValidadorTokenSamlService(){
        super(WSVALIDADORTOKENSAMLSERVICE_WSDL_LOCATION,new QName("http://co.experian.computec.saml.ws.validadortoken/","WsValidadorTokenSamlService"));
    }

    /**
     * 
     * @return returns WsValidadorTokenSaml
     */
    @WebEndpoint(name="WsValidadorTokenSamlPort")
    public WsValidadorTokenSaml getWsValidadorTokenSamlPort(){
        return super.getPort(new QName("http://co.experian.computec.saml.ws.validadortoken/","WsValidadorTokenSamlPort"),WsValidadorTokenSaml.class);
    }

}
